theme: jekyll-theme-slate
title: Jeffrey Lynn - Home
description: Personal website and digital portfolio. See what I am working on, where to contact me, and why I do what I do. This site is a work in progress: not much content yet.
